[paths]
provisioning = /etc/grafana/provisioning

[server]
http_port = 3000
domain = localhost

[auth.anonymous]
# activate as guest for viewing only (optional)
enabled = true
org_role = Viewer

[security]
admin_user = admin
admin_password = admin
allow_embedding = true

[dashboards]
min_refresh_interval = 5s
